name: universal_web
description: "A flutter package that provides a universal web utilities for flutter with native compatibility."
version: 0.1.0
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0